[package]
name = "opdater_test"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
reporsitory = { workspace = true }
include = ["src/**/*.rs", "../../README.md"]
publish = false

[dependencies]
opdater = { workspace = true }